[profile.default]
src = 'src/contracts'
script = 'src/script'
out = 'out'
test = 'src/test'
cache_path = 'forge-cache'
libs = ["node_modules", "lib"]
remappings = [
    '@aave/=node_modules/@aave/',
    '@aave/core-v3/=node_modules/@aave/core-v3',
    '@aave/periphery-v3/=node_modules/@aave/periphery-v3',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'aave-stk-v1-5/=lib/aave-stk-v1-5/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=lib/forge-std/src/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

solc_version = "0.8.10"
extra_output_files = ["metadata"]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config